name: Build a docker image of Caddy with Cloudflare plugin

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  docker-build-caddy-with-cloudflare-plugin:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: caddy-cf
      CADDY_URL: "https://caddyserver.com/api/download?os=linux&arch=amd64&p=github.com%2Fcaddy-dns%2Fcloudflare"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN  }}
      - name: Get last updated date of Caddy binary
        run: |
          echo "CADDY_HASH=$(curl -sSL -D - '${{ env.CADDY_URL }}' -o /dev/null | \
            grep last-modified | cut -d' ' -f 2- | sha1sum | cut -d' ' -f1)" | tee -a $GITHUB_ENV
        shell: bash
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./caddy
          push: true
          platforms: linux/amd64,linux/arm64/v8
          build-args: |
            CADDY_HASH=${{ env.CADDY_HASH }}
            CADDY_URL=${{ env.CADDY_URL }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.CADDY_HASH }}
