name: Build a docker image of Coredns with plugins

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  docker-build-coredns-with-plugins:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/coredns
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN  }}
      - name: Set metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: asia-northeast1-docker.pkg.dev
          tags: |
            type=semver,pattern={{raw}}
            type=sha,format=short
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./coredns
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm64/v8,linux/arm/v7
          tags: |
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
